# Generated by Django 4.0.6 on 2022-09-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthreport',
            name='description',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='expected_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='healthreport',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='roomcleaning',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
